export const SET_HASH_KEY_SUCCESS = 'APPSTATE/SET_HASH_KEY_SUCCESS';
export const SET_ONBOARDING_ERROR = 'ONBOARDING/SET_ONBOARDING_ERROR';
export const SET_SEED_WORDS = 'ONBOARDING/SET_SEED_WORDS';
export const UPDATE_PASSWORD_METER_SCORE = 'ONBAORDING/UPDATE_PASSWORD_METER_SCORE';
