export const ADD_ACCOUNT = 'ACCOUNT/ADD_ACCOUNT';
export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_SUCCESS = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_SUCCESS';
export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_ERROR = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_ERROR';
export const SELECT_ACCOUNT = 'ACCOUNT/SELECT_ACCOUNT';
export const UPDATE_ACCOUNT_BALANCE = 'ACCOUNT/UPDATE_ACCOUNT_BALANCE';
