export const ADD_ACCOUNT = 'ACCOUNT/ADD';
export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_SUCCESS = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_SUCCESS';
export const CREATE_FIRST_ACCOUNT_SEED_PHRASE_ERROR = 'ACCOUNT/FIRST_ACCOUNT_SEED_PHRASE_ERROR';
export const SELECT_ACCOUNT = 'ACCOUNT/SELECT';
export const UPDATE_ACCOUNT_BALANCE = 'ACCOUNT/UPDATE_BALANCE';
export const UPDATE_SELECTED_ACCOUNT_BALANCE = 'ACCOUNT/UPDATE_SELECTED_ACCOUNT_BALANCE';
