export const APPSTATE_CHANGE_PAGE_STATUS = 'APPSTATE/CHANGE_PAGE_STATUS';
export const APPSTATE_IS_LOADING = 'APPSTATE/IS_LOADING';
export const APPSTATE_IS_APP_ONBOARDED = 'APPSTATE/IS_APP_ONBOARDED';
