export const BG_APP_IS_ONBOARDED = 'APP/IS_ONBOARDED';
export const BG_APP_IS_READY = 'APP/IS_READY';
export const BG_SET_HASH_KEY = 'APP/SET_HASH_KEY';

export const BG_ACCOUNTS_CREATE_ACCOUNT = 'ACCOUNTS/CREATE_ACCOUNT';
export const BG_ACCOUNTS_CREATE_SEED_WORDS = 'ACCOUNTS/CREATE_SEED_WORDS';

export const BG_ACCOUNTS_CURRENT_ACCOUNT = 'ACCOUNT/CURRENT';
export const BG_ACCOUNTS_LIST = 'ACCOUNTS/LIST';

export const BG_ACCOUNT_BALANCE = 'ACCOUNT/BALANCE';

export const BG_NETWORKS_CURRENT = 'NETWORK/CURRENT';
export const BG_NETWORKS_STATUS = 'NETWORK/STATUS';

// Transaction

export const BG_TXN_UNIT_CONVERTER = 'TXN/UNIT_CONVERTER';
export const BG_TXN_FEE = 'TXN/GET_FEES';
export const BG_TXN_SUBMIT = 'TXN/SUBMIT';
export const BG_TXN_LIST_TXNS = 'TXNS/LIST_TXNS';
export const BG_TXN_STATUS = 'TXN/STATUS';
