export const BG_APP_SET_ONBOARDED = 'APP/ONBOARDED';
export const BG_APP_IS_ONBOARDED = 'APP/IS_ONBOARDED';
export const BG_APP_IS_READY = 'APP/IS_READY';
export const BG_SET_HASH_KEY = 'APP/SET_HASH_KEY';

export const BG_ACCOUNTS_CREATE_ACCOUNT = 'ACCOUNTS/CREATE_ACCOUNT';
export const BG_ACCOUNTS_CREATE_SEED_WORDS = 'ACCOUNTS/CREATE_SEED_WORDS';
export const BG_ACCOUNTS_UPDATE_ALIAS = 'ACCOUNTS/UPDATE_ALIAS';

export const BG_ACCOUNTS_CURRENT_ACCOUNT = 'ACCOUNT/CURRENT';
export const BG_ACCOUNTS_LIST = 'ACCOUNTS/LIST';

export const BG_ACCOUNT_BALANCE = 'ACCOUNT/BALANCE';

export const BG_NETWORK_CURRENT = 'NETWORK/CURRENT';
export const BG_NETWORK_IS_CONNECTED = 'NETWORK/IS_CONNECTED';
export const BG_NETWORK_UPDATE = 'NETWORK/UPDATE';

// Transaction

export const BG_TXN_FEE = 'TXN/GET_FEES';
export const BG_TXN_CONFIRM = 'TXN/CONFIRM';
export const BG_TXN_SUBMIT = 'TXN/SUBMIT';
export const BG_TXN_GET = 'TXN/GET';
export const BG_TXN_LIST = 'TXNS/LIST';

// Validation

export const BG_ACCOUNT_IS_VALID_ADDRESS = 'ACCOUNT/ADDRESS';
