export const ADD_ACCOUNT = 'ACCOUNT/ADD';
export const SELECT_ACCOUNT = 'ACCOUNT/SELECT';
export const UPDATE_ACCOUNT_BALANCE = 'ACCOUNT/UPDATE_BALANCE';
export const UPDATE_SELECTED_ACCOUNT_BALANCE = 'ACCOUNT/UPDATE_SELECTED_ACCOUNT_BALANCE';
export const UPDATE_IS_LINK_TO_BLOCKXLABS_FAUCET = 'ACCOUNT/UPDATE_IS_TO_LINK_BLOCKXLABS_FAUCET';
