export const TERMS_PAGE = 'TERMS_PAGE';

export const DASHBOARD_PAGE = 'DASHBOARD_PAGE';
export const SEND_TRANSACTION_PAGE = 'SEND_TRANSACTION_PAGE';
export const CONFIRM_PAGE = 'CONFIRM_PAGE';
export const DEPOSIT_PAGE = 'DEPOSIT_PAGE';
export const EXPORT_KEY_PAGE = 'EXPORT_KEY_PAGE';
export const CREATE_KEY_STORE_PAGE = 'CREATE_KEY_STORE_PAGE';
export const SETTINGS_PAGE = 'SETTINGS_PAGE';
export const EXPORT_VAULT_PAGE = 'EXPORT_VAULT_PAGE';
export const SIGN_UP_PAGE = 'SIGN_UP_PAGE';
export const SIGN_IN_PAGE = 'SIGN_IN_PAGE';
export const SEED_WORDS = 'SEED_WORDS';
export const REVEAL_SEED_WORDS = 'REAVEAL_SEED_WORDS';
export const LOADER_OVERLAY = 'LOADER_OVERLAY';
export const CREATE_ACCOUNT_PAGE = 'CREATE_ACCOUNT_PAGE';

// Define Group related to onboarding
export const ONBOARDING_PAGES_GROUP = [TERMS_PAGE, SIGN_IN_PAGE, REVEAL_SEED_WORDS];
