export const TERMS_PAGE = 'TERMS_PAGE';
export const DASHBOARD_PAGE = 'DASHBOARD_PAGE';
export const TRANSFER_PAGE = 'TRANSFER_PAGE';
export const CONFIRM_PAGE = 'CONFIRM_PAGE';
export const SIGN_UP_PAGE = 'SIGN_UP_PAGE';
export const SIGN_IN_PAGE = 'SIGN_IN_PAGE';
export const LOADER_OVERLAY = 'LOADER_OVERLAY';
export const CREATE_ACCOUNT_PAGE = 'CREATE_ACCOUNT_PAGE';
export const ERROR_PAGE = 'ERROR_PAGE';
export const CUSTOM_NETWORK_PAGE = 'CUSTOM_NETWORK_PAGE';
export const QR_CODE_PAGE = 'QR_CODE_PAGE';
export const ABOUT_PAGE = 'about';

export const ONBOARDING_PAGES_GROUP = [TERMS_PAGE, SIGN_IN_PAGE, SIGN_UP_PAGE, CREATE_ACCOUNT_PAGE];
