export const UPDATE_NETWORK_LIST = 'NETWORK/UPDATE_LIST';
export const CHANGE_NETWORK = 'NETWORK/CHANGE';
export const UPDATE_CUSTOM_NETWORK = 'NETWORK/UPDATE_CUSTOM_NETWORK';
export const UPDATE_NETWORK_STATUS = 'NETWORK/UPDATE_STATUS';
export const CUSTOM_NETWORK_VALIDATION_ERROR = 'NETWORK/CUSTOM_NETWORK_VALIDATION_ERROR';
export const CUSTOM_NETWORK_VALIDATION_SUCCESS = 'NETWORK/CUSTOM_NETWORK_VALIDATION_SUCCESS';
