export const COIN_TRANSFER_DETAILS = 'TRANSFER/DETAILS';
export const CLEAR_COIN_TRANSFER_DETAILS = 'TRANSFER/CLEAR_DETAILS';
export const UPDATE_TRANSFER_FEE = 'TRANSFER/UPDATE_TRANSFER_FEE';
export const UPDATE_TRANSFER_AMOUNT = 'TRANSFER/UPDATE_TRANSFER_AMOUNT';
